######################################################################
# Automatically generated by qmake (2.01a) Wed Jul 13 23:47:33 2011
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .
QT += opengl

LIBS += -lgeos

# Input
SOURCES += edatool.cpp editorarea.cpp main.cpp index.cpp polygon.cpp track.cpp board.cpp layer.cpp
HEADERS += edatool.h editorarea.h index.h polygon.h track.h board.h layer.h
